name: projectname
services:
  app:
    image: allape/projectname:latest
    container_name: projectname
    restart: unless-stopped
    environment:
      PROJECTNAME_DATABASE_DSN: "root:2mu4XX0HBmajg7hcbFFn@tcp(database:3306)/projectname?charset=utf8mb4&parseTime=True&loc=Local"
      PROJECTNAME_STATIC_FILE_MASTER_KEY: "LU2SpvQeN5n9wgz1d7Wq"
      PROJECTNAME_STATIC_FILE_HASH_SALT: "yWQj0aXffk4oaAx66NIl"
    volumes:
      - ./static:/app/static
    networks:
      - https
      - internal
    depends_on:
      database:
        condition: service_healthy
  database:
    image: allape/autodumpmysql:8
    restart: unless-stopped
    networks:
      - internal
    healthcheck:
      test: mysql -uroot -p"$$MYSQL_ROOT_PASSWORD" -e "SELECT 1" > /dev/null 2>&1 || exit 1
    environment:
      - MYSQL_ROOT_PASSWORD=2mu4XX0HBmajg7hcbFFn
      - MYSQL_DATABASE=projectname
    volumes:
      - ./database:/var/lib/mysql
networks:
  https:
  internal:
    internal: true
